export const organizations = [
  {name: 'Shopify', industries: ['e-commerce', 'software']},
  {name: 'Lambda School', industries: ['training', 'software development']},
  {name: 'E-Bay', industries: ['trading', 'platforms']},
  {name: 'Microsoft', industries: ['productivity', 'software', 'operating systems']},
  {name: 'GitHub', industries: ['social media', 'software development', 'open source']},
  {name: 'XBox', industries: ['video games']},
  {name: 'Oracle', industries: ['databases', 'ERP']},
  {name: 'Amazon', industries: ['e-commerce', 'delivery', 'wharehouse space']},
  {name: 'Facebook', industries: ['social media']},
  {name: 'Twitter', industries: ['social media']},
  {name: 'Uber', industries: ['the gig economy', 'ride sharing', 'platforms']},
  {name: 'UberEATS', industries: ['the gig economy', 'food', 'pizza', 'platforms']},
  {name: 'Apple', industries: ['operating systems', 'hardware']},
  {name: 'Square', industries: ['payments']},
  {name: 'Stripe', industries: ['payments']},
  {name: 'Coinbase', industries: ['crypto currency']},
  {name: 'Instagram', industries: ['social media', 'photo sharing', 'photography']},
  {name: 'Instacart', industries: ['the gig economy', 'delivery']},
  {name: 'Netflix', industries: ['content', 'video', 'streaming']},
  {name: 'YouTube', industries: ['content', 'video', 'streaming']},
  {name: 'Salesforce', industries: ['CRM', 'sales people']},
  {name: 'Verizon', industries: ['telecom']},
  {name: 'AT&T', industries: ['telecom']},
  {name: 'Comcast', industries: ['telecom']},
  {name: 'Airbnb', industries: ['the gig economy', 'rentals', 'hotels']},
  {name: 'Zoom', industries: ['video conferencing']},
  {name: 'Spotify', industries: ['content', 'audio', 'music', 'podcasting', 'streaming']},
  {name: 'Intuit', industries: ['tax filing', 'accountants']},
  {name: 'PayPal', industries: ['money transfers']},
  {name: 'Mailchimp', industries: ['email marketing', 'marketing']},
  {name: 'WordPress', industries: ['CMS']},
  {name: 'Adobe', industries: ['graphic designers', 'graphic tools']},
  {name: 'Dropbox', industries: ['file storage']},
  {name: 'Amazon AWS', industries: ['file storage', 'hosting', 'sysops']},
  {name: 'WealthSimple', industries: ['investing']},
  {name: 'PriceLine', industries: ['hotels', 'rentals']},
]

export const industries = {
  'accessory stores':[], 'accounting services':[], 'adhesive manufacturing':[], 'advertising agencies':[], 'agencies':[], 'agricultural feed sales':[],
  'agricultural machinery manufacturing':[], 'air-conditioning':[], 'air-conditioning contractors':[], 'air-conditioning equipment manufacturing':[],
  'alloying':[], 'aluminum manufacturing':[], 'animal feed production':[], 'annuities':[], 'apartment rental':[], 'appliance sales':[], 'arcades':[],
  'architects':[], 'asphalt manufacturing':[], 'atv dealers':[], 'auto detailing':[], 'auto mechanics':[], 'automobile electronics manufacturing':[],
  'automobile manufacturing':[], 'automobile sales':[], 'auto parts manufacturing':[], 'auto parts sales':[], 'auto parts stores':[],
  'bag manufacturing':[], 'ball bearing manufacturing':[], 'battery manufacturing':[], 'beauty product manufacturing':[], 'beef cattle production':[],
  'belt manufacturing':[], 'benefits administration':[], 'block manufacturing':[], 'boarding':[], 'boat building':[], 'bolt manufacturing':[],
  'bookkeeping services':[], 'book publishing':[], 'book stores':[], 'bottled water production':[], 'boys\' apparel manufacturing':[],
  'brand-name pharmaceutical manufacturing':[], 'bread production':[], 'breweries':[], 'bridal stores':[], 'brokerage':[],
  'building material stores':[], 'bulb manufacturing':[], 'business coaching':[], 'bus manufacturing':[], 'cable manufacturing':[],
  'cable networks':[], 'call centres':[], 'candy production':[], 'cannabis production':[], 'car body shops':[], 'card stores':[],
  'career counselling':[], 'car rental':[], 'caterers':[], 'cement manufacturing':[], 'ceramics manufacturing':[], 'cereal production':[],
  'chemical product manufacturing':[], 'chemical sales':[], 'chicken egg production':[], 'chocolate production':[], 'cleaning compound manufacturing':[],
  'clothing accessories sales':[], 'coal mining':[], 'coastal transportation':[], 'commercial banking':[], 'commercial building construction':[],
  'communications equipment manufacturing':[], 'compressor manufacturing':[], 'computer manufacturing':[], 'computer peripheral manufacturing':[],
  'computer repair services':[], 'concrete contractors':[], 'condominium construction':[], 'construction machinery manufacturing':[], 'consulting':[],
  'consumer electronics stores':[], 'contact lens manufacturing':[], 'contact lens stores':[], 'container manufacturing':[], 'convenience stores':[],
  'conveyor manufacturing':[], 'cooking oil processing':[], 'corn farming':[], 'country clubs':[], 'craft supplies sales':[], 'credit unions':[],
  'cutlery manufacturing':[], 'dairy farms':[], 'dairy product production':[], 'dairy sales':[], 'dating services':[], 'day care':[],
  'debt collection agencies':[], 'dentists':[], 'department stores':[], 'development':[], 'direct mail advertising':[], 'directory publishing':[],
  'direct selling companies':[], 'disposal services':[], 'distilleries':[], 'door manufacturing':[], 'drawing':[], 'drug stores':[], 'dry cleaners':[],
  'economic consulting':[], 'electrical equipment manufacturing':[], 'electrical equipment sales':[], 'electricians':[], 'electric power transmission':[],
  'elevated highway construction':[], 'engineering services':[], 'environmental cleanup services':[], 'environmental consulting':[], 'equipment sales':[],
  'event planning':[], 'event promotion':[], 'family clothing stores':[], 'family fun centres':[], 'farm supplies sales':[], 'fast food restaurants':[],
  'ferrous metal foundry products':[], 'fertilizer manufacturing':[], 'fitness clubs':[], 'flavouring production':[], 'floor covering sales':[],
  'floor covering stores':[], 'florists':[], 'flour milling':[], 'flower growing':[], 'food service contractors':[], 'footwear manufacturing':[],
  'footwear sales':[], 'foreign currency exchange services':[], 'forestry equipment sales':[], 'forging':[], 'fragrance stores':[],
  'frozen food production':[], 'frozen food sales':[], 'full-service restaurants':[], 'funeral homes':[], 'furnishings sales':[], 'furniture stores':[],
  'gambling':[], 'game manufacturing':[], 'garages':[], 'garden equipment':[], 'garden stores':[], 'gas extraction':[], 'gas field services':[],
  'gas machinery manufacturing':[], 'gas machinery sales':[], 'gas pipeline construction':[], 'gas stations':[], 'gas stations with convenience stores':[],
  'general-line building supplies':[], 'generic pharmaceutical manufacturing':[], 'geophysical services':[], 'glass product manufacturing':[],
  'graphic designers':[], 'gravel mining':[], 'grocery sales':[], 'grocery stores':[], 'hardware manufacturing':[], 'hardware sales':[],
  'hardware stores':[], 'health stores':[], 'heat exchanger manufacturing':[], 'heavy engineering construction':[], 'heavy equipment rental':[],
  'heavy equipment repair services':[], 'highway construction':[], 'homebuilders':[], 'home care providers':[], 'home furnishings stores':[],
  'home improvement stores':[], 'hospitals':[], 'hosting services':[], 'hotel equipment sales':[], 'household furniture manufacturing':[],
  'hr consulting':[], 'hydrogen gas manufacturing':[], 'ice cream production':[], 'industrial building construction':[],
  'infants\' apparel manufacturing':[], 'infants\' clothing stores':[], 'inorganic chemical manufacturing':[], 'insulation sales':[],
  'interior designers':[], 'iron ore mining':[], 'irrigation systems':[], 'it consulting':[], 'janitorial services':[], 'jewellery manufacturing':[],
  'jewellery stores':[], 'juice production':[], 'labelling services':[], 'laboratory supply sales':[], 'laboratory testing services':[],
  'laminated paper manufacturing':[], 'landscaping services':[], 'language instruction':[], 'law firms':[], 'lead refining':[], 'leasing':[],
  'lighting fixtures manufacturing':[], 'light truck manufacturing':[], 'limousine services':[], 'linen supply':[], 'liquor stores':[],
  'local delivery services':[], 'local freight trucking':[], 'local specialized freight trucking':[], 'logging':[], 'logistics services':[],
  'long-distance freight trucking':[], 'lubricant oil manufacturing':[], 'lumber sales':[], 'machine shop services':[],
  'major household appliance manufacturing':[], 'management consulting':[], 'mapping services':[], 'market research':[], 'mattress manufacturing':[],
  'medical device manufacturing':[], 'medical supplies sales':[], 'men\'s clothing stores':[], 'metal ore mining':[], 'metal sales':[],
  'metal tank manufacturing':[], 'metalworking machinery manufacturing':[], 'millwork':[], 'missile manufacturing':[], 'motels':[],
  'motor home manufacturing':[], 'movie theatres':[], 'moving services':[], 'municipal building construction':[], 'music publishing':[],
  'nail salons':[], 'natural gas distribution':[], 'navigational instrument manufacturing':[], 'new car dealers':[], 'newspaper publishing':[],
  'nightclubs':[], 'nonferrous metal foundry product manufacturing':[], 'nursery stock sales':[], 'nut farming':[], 'office furniture manufacturing':[],
  'office stationery manufacturing':[], 'office stationery sales':[], 'office supply stores':[], 'oil change services':[], 'online auctions':[],
  'optometrists':[], 'organic chemical manufacturing':[], 'other':[], 'other electronic':[], 'other general-purpose':[],
  'other plastic product manufacturing':[], 'other publishing':[], 'other services':[], 'outdoor advertising':[], 'outdoor equipment stores':[],
  'overhaul':[], 'packaged software sales':[], 'paint manufacturing':[], 'paperboard mills':[], 'paper mills':[], 'paper product manufacturing':[],
  'parts manufacturing':[], 'pasta production':[], 'periodical publishing':[], 'pest control':[], 'pesticide manufacturing':[],
  'petrochemical manufacturing':[], 'petroleum bulk stations':[], 'petroleum refining':[], 'petroleum sales':[], 'pet stores':[],
  'pharmacy supplies sales':[], 'phosphate mining':[], 'photography':[], 'physical therapists':[], 'pig farming':[],
  'plastic bottle manufacturing':[], 'plumbing':[], 'pork sales':[], 'poultry processing':[], 'precast concrete manufacturing':[],
  'prefabricated home manufacturing':[], 'prepared food manufacturing':[], 'primary care doctors':[], 'printing':[],
  'printing services':[], 'product manufacturing':[], 'promotional products':[], 'property, casualty and direct insurance':[], 'property management':[],
  'public relations firms':[], 'public transportation':[], 'radio broadcasting':[], 'rail transportation':[], 'ready-mix concrete manufacturing':[],
  'real estate appraisal':[], 'real estate investment trusts':[], 'recreational vehicle dealers':[], 'recreational vehicle parks':[],
  'recruiting agencies':[], 'recyclable material sales':[], 'recycling facilities':[], 'refrigeration trucking':[], 'renewable power':[],
  'resin manufacturing':[], 'roofing contractors':[], 'rubber machinery manufacturing':[], 'rubber product manufacturing':[],
  'sandpaper manufacturing':[], 'sanitary paper product manufacturing':[], 'satellite tv providers':[], 'scheduled air transportation':[],
  'seafood aquaculture':[], 'seafood preparation':[], 'seafood sales':[], 'seasoning, sauce and condiment':[], 'security alarm services':[],
  'security services':[], 'semiconductor machinery manufacturing':[], 'sewage treatment facilities':[], 'sewing supplies stores':[],
  'shade manufacturing':[], 'ship building':[], 'shoe stores':[], 'sign manufacturing':[], 'silver ore mining':[], 'small specialty retail stores':[],
  'snack food production':[], 'snack shops':[], 'snowboard resorts':[], 'snowmobile manufacturing':[], 'soda production':[], 'software publishing':[],
  'soybean farming':[], 'specialty food stores':[], 'spectator sports':[], 'spirits sales':[], 'sporting goods manufacturing':[],
  'sporting goods sales':[], 'sporting goods stores':[], 'spring manufacturing':[], 'steel manufacturing':[], 'stone mining':[], 'street vendors':[],
  'structural metal product manufacturing':[], 'substance abuse centres':[], 'substance abuse clinics':[], 'supercentres':[], 'supplies stores':[],
  'supply manufacturing':[], 'synthetic fibre manufacturing':[], 'tax preparation services':[], 'tea production':[], 'telecommunications networking':[],
  'temp agencies':[], 'textile mills':[], 'thermal power':[], 'tire dealers':[], 'tire manufacturing':[], 'tire sales':[], 'tobacco manufacturing':[],
  'tobacco product sales':[], 'tour operators':[], 'toy stores':[], 'transit car manufacturing':[], 'transmission line construction':[],
  'travel agencies':[], 'treating':[], 'truck rental':[], 'tube manufacturing':[], 'turbine manufacturing':[], 'turkey meat production':[],
  'tv broadcasting':[], 'universities':[], 'used car dealers':[], 'used goods stores':[], 'utilities':[], 'valve manufacturing':[], 'vanity manufacturing':[],
  'variety stores':[], 'vegetable farming':[], 'vegetable processing':[], 'vegetable sales':[], 'vending machine operators':[], 'veterinary services':[],
  'video distribution':[], 'video equipment manufacturing':[], 'video postproduction services':[], 'video production':[], 'video rental':[],
  'visitor bureaus':[], 'warehouse leasing':[], 'warehousing':[], 'waste collection services':[], 'watch sales':[], 'weight loss services':[],
  'wheat farming':[], 'wind turbine manufacturing':[], 'wired telecommunications carriers':[], 'wireless telecommunications carriers':[],
  'wiring device manufacturing':[], 'women\'s clothing stores':[], 'wood panelling manufacturing':[], 'wood production':[], 'wood pulp mills':[],
  'zinc mining':[]
}

organizations.forEach(organization => {
  organization.industries.forEach(industry => {
    if (industries[industry]) {
      industries[industry].push(organization)
    } else {
      industries[industry] = [organization]
    }
  })
})

export const emojis = [
  '✨',
  '🔥',
  '🙌',
  '😂',
  '😹',
  '📢',
  '🌟',
  '🎈',
  '🎉',
  '🎆',
  '😅'
]
